workflows:
    ios-project: # workflow ID
        name: iOS project # workflow name
        max_build_duration: 120
        instance_type: mac_mini_m1
        environment:
            xcode: latest
            cocoapods: default
        scripts:
            - xcodebuild build -workspace "XcodeBenchmark.xcworkspace" -scheme "XcodeBenchmark" -destination generic/platform=iOS
